services:
    ezytutors.api:
        image: ${DOCKER_REGISTRY-}tutorapi
        container_name: Ezytutors.Api
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            ezytutors.db:
                condition: service_healthy
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - RUST_LOG=${RUST_LOG}
            - SERVER_HOSTNAME_PORT=${SERVER_HOSTNAME_PORT}
        ports:
            - "8080:8080"
        restart: unless-stopped

    ezytutors.db:
        image: postgres:latest
        container_name: Ezytutors.Db
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - ./.containers/database:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 30s
            timeout: 10s
            retries: 3